// --- FAILSAFE DATA (Offline Mode) ---
// Used when iNaturalist API is down (503 Service Unavailable)

export const BACKUP_ANIMALS = [
    {
        id: "backup_1",
        name: "Lion",
        correctName: "Lion",
        sciName: "Panthera leo",
        family: "Felidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/7/73/Lion_waiting_in_Namibia.jpg",
        lat: -2.333,
        lng: 34.833,
        location: "Serengeti National Park, Tanzania",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Lion",
        stats: { trait: "Known as the 'King of Beasts', they live in prides.", date: "2024", year: 2024 }
    },
    {
        id: "backup_2",
        name: "Emperor Penguin",
        correctName: "Emperor Penguin",
        sciName: "Aptenodytes forsteri",
        family: "Spheniscidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/07/Emperor_Penguin_Manchot_empereur.jpg",
        lat: -77.0,
        lng: 166.0,
        location: "Ross Sea, Antarctica",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Emperor_penguin",
        stats: { trait: "The tallest and heaviest of all living penguin species.", date: "2024", year: 2024 }
    },
    {
        id: "backup_3",
        name: "Monarch Butterfly",
        correctName: "Monarch Butterfly",
        sciName: "Danaus plexippus",
        family: "Nymphalidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/6/63/Monarch_In_May.jpg",
        lat: 19.6,
        lng: -100.2,
        location: "Michoacán, Mexico",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Monarch_butterfly",
        stats: { trait: "Known for its long-distance annual migration.", date: "2024", year: 2024 }
    },
    {
        id: "backup_4",
        name: "Koala",
        correctName: "Koala",
        sciName: "Phascolarctos cinereus",
        family: "Phascolarctidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/49/Koala_climbing_tree.jpg",
        lat: -27.4,
        lng: 153.0,
        location: "Queensland, Australia",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Koala",
        stats: { trait: "Sleeps up to 20 hours a day and eats eucalyptus.", date: "2024", year: 2024 }
    },
    {
        id: "backup_5",
        name: "Great White Shark",
        correctName: "Great White Shark",
        sciName: "Carcharodon carcharias",
        family: "Lamnidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/5/56/White_shark.jpg",
        lat: -34.5,
        lng: 19.3,
        location: "Gansbaai, South Africa",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Great_white_shark",
        stats: { trait: "The world's largest known predatory fish.", date: "2024", year: 2024 }
    },
    {
        id: "backup_6",
        name: "Bald Eagle",
        correctName: "Bald Eagle",
        sciName: "Haliaeetus leucocephalus",
        family: "Accipitridae",
        image: "https://upload.wikimedia.org/wikipedia/commons/1/1a/About_to_Launch_%2826075320352%29.jpg",
        lat: 57.0,
        lng: -135.0,
        location: "Sitka, Alaska, USA",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Bald_eagle",
        stats: { trait: "The national bird of the United States.", date: "2024", year: 2024 }
    },
    {
        id: "backup_7",
        name: "Red-Eyed Tree Frog",
        correctName: "Red-Eyed Tree Frog",
        sciName: "Agalychnis callidryas",
        family: "Phyllomedusidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Red-eyed_Tree_Frog_%28Agalychnis_callidryas%29_1.jpg",
        lat: 10.0,
        lng: -84.0,
        location: "Monteverde, Costa Rica",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Agalychnis_callidryas",
        stats: { trait: "Has bright red eyes and neon green skin.", date: "2024", year: 2024 }
    },
    {
        id: "backup_8",
        name: "Komodo Dragon",
        correctName: "Komodo Dragon",
        sciName: "Varanus komodoensis",
        family: "Varanidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/1/18/Komodo_Dragon_en_face.jpg",
        lat: -8.5,
        lng: 119.5,
        location: "Komodo Island, Indonesia",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Komodo_dragon",
        stats: { trait: "The largest living species of lizard.", date: "2024", year: 2024 }
    },
    {
        id: "backup_9",
        name: "Giant Panda",
        correctName: "Giant Panda",
        sciName: "Ailuropoda melanoleuca",
        family: "Ursidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/0f/Grosser_Panda.JPG",
        lat: 30.0,
        lng: 103.0,
        location: "Sichuan, China",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Giant_panda",
        stats: { trait: "99% of its diet consists of bamboo.", date: "2024", year: 2024 }
    },
    {
        id: "backup_10",
        name: "Blue Whale",
        correctName: "Blue Whale",
        sciName: "Balaenoptera musculus",
        family: "Balaenopteridae",
        image: "https://upload.wikimedia.org/wikipedia/commons/1/1c/Anim1754_-_Flickr_-_NOAA_Photo_Library.jpg",
        lat: 33.0,
        lng: -118.0,
        location: "Pacific Ocean, California",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Blue_whale",
        stats: { trait: "The largest animal known to have ever lived.", date: "2024", year: 2024 }
    },
    {
        id: "backup_11",
        name: "Honey Bee",
        correctName: "Honey Bee",
        sciName: "Apis mellifera",
        family: "Apidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Apis_mellifera_Western_honey_bee.jpg",
        lat: 45.0,
        lng: 2.0,
        location: "Provence, France",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Western_honey_bee",
        stats: { trait: "Produces honey and pollinates flowers.", date: "2024", year: 2024 }
    },
    {
        id: "backup_12",
        name: "Meerkat",
        correctName: "Meerkat",
        sciName: "Suricata suricatta",
        family: "Herpestidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Suricata_suricatta_Mongoose.jpg",
        lat: -25.0,
        lng: 20.0,
        location: "Kalahari Desert, Botswana",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Meerkat",
        stats: { trait: "Known for standing upright to watch for predators.", date: "2024", year: 2024 }
    },
    {
        id: "backup_13",
        name: "Galapagos Tortoise",
        correctName: "Galapagos Tortoise",
        sciName: "Chelonoidis niger",
        family: "Testudinidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/4/42/Galapagos_giant_tortoise_Geochelone_elephantopus.jpg",
        lat: -0.5,
        lng: -90.5,
        location: "Galápagos Islands, Ecuador",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Galápagos_tortoise",
        stats: { trait: "Can live for over 100 years.", date: "2024", year: 2024 }
    },
    {
        id: "backup_14",
        name: "Snow Leopard",
        correctName: "Snow Leopard",
        sciName: "Panthera uncia",
        family: "Felidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/a5/Irbis4.JPG",
        lat: 35.0,
        lng: 76.0,
        location: "Himalayas, Pakistan",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Snow_leopard",
        stats: { trait: "Known as the 'Ghost of the Mountains'.", date: "2024", year: 2024 }
    },
    {
        id: "backup_15",
        name: "Capybara",
        correctName: "Capybara",
        sciName: "Hydrochoerus hydrochaeris",
        family: "Caviidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/e/ec/Capybara_%28Hydrochoerus_hydrochaeris%29.JPG",
        lat: -15.0,
        lng: -56.0,
        location: "Pantanal, Brazil",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Capybara",
        stats: { trait: "The largest living rodent in the world.", date: "2024", year: 2024 }
    },
    {
        id: "backup_16",
        name: "Platypus",
        correctName: "Platypus",
        sciName: "Ornithorhynchus anatinus",
        family: "Ornithorhynchidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Platypus-sketch.jpg",
        lat: -42.0,
        lng: 146.0,
        location: "Tasmania, Australia",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Platypus",
        stats: { trait: "One of the few mammals that lay eggs.", date: "2024", year: 2024 }
    },
    {
        id: "backup_17",
        name: "Green Sea Turtle",
        correctName: "Green Sea Turtle",
        sciName: "Chelonia mydas",
        family: "Cheloniidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Green_Sea_Turtle_swimming.jpg",
        lat: 21.0,
        lng: -157.0,
        location: "Hawaii, USA",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Green_sea_turtle",
        stats: { trait: "Named for the color of its fat, not its shell.", date: "2024", year: 2024 }
    },
    {
        id: "backup_18",
        name: "Peregrine Falcon",
        correctName: "Peregrine Falcon",
        sciName: "Falco peregrinus",
        family: "Falconidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/07/Peregrine_Falcon_USFWS.jpg",
        lat: 40.7,
        lng: -74.0,
        location: "New York City, USA",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Peregrine_falcon",
        stats: { trait: "The fastest member of the animal kingdom.", date: "2024", year: 2024 }
    },
    {
        id: "backup_19",
        name: "African Elephant",
        correctName: "Elephant",
        sciName: "Loxodonta africana",
        family: "Elephantidae",
        image: "https://upload.wikimedia.org/wikipedia/commons/b/bf/African_Elephant_%28Loxodonta_africana%29_male_%2817289351322%29.jpg",
        lat: -19.0,
        lng: 23.0,
        location: "Okavango Delta, Botswana",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/African_elephant",
        stats: { trait: "The largest land animal on Earth.", date: "2024", year: 2024 }
    },
    {
        id: "backup_20",
        name: "Ring-Tailed Lemur",
        correctName: "Lemur",
        sciName: "Lemur catta",
        family: "Lemuridae",
        image: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Ring-tailed_lemur_%28Lemur_catta%29.jpg",
        lat: -22.0,
        lng: 45.0,
        location: "Madagascar",
        recordedBy: "Offline_Backup",
        link: "https://en.wikipedia.org/wiki/Ring-tailed_lemur",
        stats: { trait: "Endemic to the island of Madagascar.", date: "2024", year: 2024 }
    }
];